<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
	  <Compile Remove="Services\TermService.cs" />
	</ItemGroup>

	<ItemGroup>
		<None Include="Services\TermService.cs" />
		<None Include="Services\TermModuleService.cs" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="FluentValidation" Version="12.0.0" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.1" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\AuroraUniversity.Domain\AuroraUniversity.Domain.csproj" />
	</ItemGroup>

</Project>
