// <auto-generated />
using System;
using AuroraUniversity.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AuroraUniversity.Infrastructure.Data.Migrations
{
    [DbContext(typeof(UniversityDbContext))]
    partial class UniversityDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AuroraUniversity.Domain.Entities.Assessment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ModuleId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Weight")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("ModuleId");

                    b.ToTable("Assessments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("78fdc1b0-b9ae-4010-827b-c1e77b798f16"),
                            Date = new DateTime(2025, 10, 30, 6, 38, 20, 839, DateTimeKind.Utc).AddTicks(1506),
                            ModuleId = new Guid("b2a8a3ee-ad46-4ef3-80a7-a756e7b4bb07"),
                            Title = "Weekly Quizzes",
                            Weight = 0.2m
                        },
                        new
                        {
                            Id = new Guid("83fcd674-ce89-4976-9ac1-2ceee1b05adb"),
                            Date = new DateTime(2025, 11, 17, 6, 38, 20, 839, DateTimeKind.Utc).AddTicks(1523),
                            ModuleId = new Guid("b2a8a3ee-ad46-4ef3-80a7-a756e7b4bb07"),
                            Title = "Math Midterm",
                            Weight = 0.3m
                        },
                        new
                        {
                            Id = new Guid("995b580b-e65c-4d22-918d-01ea4d1436f8"),
                            Date = new DateTime(2025, 12, 17, 6, 38, 20, 839, DateTimeKind.Utc).AddTicks(1527),
                            ModuleId = new Guid("b2a8a3ee-ad46-4ef3-80a7-a756e7b4bb07"),
                            Title = "Math Final Exam",
                            Weight = 0.5m
                        },
                        new
                        {
                            Id = new Guid("67b98fcc-e250-49d1-938e-2770a43768df"),
                            Date = new DateTime(2025, 11, 7, 6, 38, 20, 839, DateTimeKind.Utc).AddTicks(1530),
                            ModuleId = new Guid("6983138a-93e7-4171-95bc-61ce2fb7cdae"),
                            Title = "Lab Report 1",
                            Weight = 0.2m
                        },
                        new
                        {
                            Id = new Guid("8c375ce0-db86-4fe7-9ed7-52f555e4b652"),
                            Date = new DateTime(2025, 11, 22, 6, 38, 20, 839, DateTimeKind.Utc).AddTicks(1534),
                            ModuleId = new Guid("6983138a-93e7-4171-95bc-61ce2fb7cdae"),
                            Title = "Problem Set Submission",
                            Weight = 0.2m
                        },
                        new
                        {
                            Id = new Guid("36a2a9b2-ae38-4459-b5ae-867f9542f27c"),
                            Date = new DateTime(2025, 12, 22, 6, 38, 20, 839, DateTimeKind.Utc).AddTicks(1540),
                            ModuleId = new Guid("6983138a-93e7-4171-95bc-61ce2fb7cdae"),
                            Title = "Physics Final Exam",
                            Weight = 0.6m
                        },
                        new
                        {
                            Id = new Guid("337ee3fc-b775-4b98-9f67-fcb8b7a20535"),
                            Date = new DateTime(2025, 11, 17, 6, 38, 20, 839, DateTimeKind.Utc).AddTicks(1548),
                            ModuleId = new Guid("60f08462-e923-4908-9eea-a27651a14b10"),
                            Title = "Programming Project Phase 1",
                            Weight = 0.35m
                        },
                        new
                        {
                            Id = new Guid("11a9f45f-1b60-4cf0-a6b0-2944314b3bda"),
                            Date = new DateTime(2025, 12, 2, 6, 38, 20, 839, DateTimeKind.Utc).AddTicks(1551),
                            ModuleId = new Guid("60f08462-e923-4908-9eea-a27651a14b10"),
                            Title = "Mid-Term Code Review",
                            Weight = 0.15m
                        },
                        new
                        {
                            Id = new Guid("e364808d-834e-4cbe-875f-50f9cccf6268"),
                            Date = new DateTime(2026, 1, 6, 6, 38, 20, 839, DateTimeKind.Utc).AddTicks(1555),
                            ModuleId = new Guid("60f08462-e923-4908-9eea-a27651a14b10"),
                            Title = "Final Programming Project",
                            Weight = 0.5m
                        },
                        new
                        {
                            Id = new Guid("06a330f0-6c03-46ad-89fc-e3bccb61a4a4"),
                            Date = new DateTime(2025, 11, 12, 6, 38, 20, 839, DateTimeKind.Utc).AddTicks(1561),
                            ModuleId = new Guid("7616de2f-756c-4c5e-b49a-8561637c9451"),
                            Title = "Group Presentation",
                            Weight = 0.3m
                        },
                        new
                        {
                            Id = new Guid("01e65b87-b32e-43fa-96d6-b2afa0e93154"),
                            Date = new DateTime(2025, 12, 7, 6, 38, 20, 839, DateTimeKind.Utc).AddTicks(1565),
                            ModuleId = new Guid("7616de2f-756c-4c5e-b49a-8561637c9451"),
                            Title = "Data Analysis Report",
                            Weight = 0.4m
                        },
                        new
                        {
                            Id = new Guid("68cb3762-ecf0-416c-903d-593d5f45d9b1"),
                            Date = new DateTime(2026, 1, 1, 6, 38, 20, 839, DateTimeKind.Utc).AddTicks(1630),
                            ModuleId = new Guid("7616de2f-756c-4c5e-b49a-8561637c9451"),
                            Title = "Statistics Final Exam",
                            Weight = 0.3m
                        });
                });

            modelBuilder.Entity("AuroraUniversity.Domain.Entities.Mark", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssessmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Comments")
                        .HasColumnType("text");

                    b.Property<DateTime>("DateRecorded")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsResit")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("RecordedByStaffId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Score")
                        .HasColumnType("numeric");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AssessmentId");

                    b.HasIndex("RecordedByStaffId");

                    b.HasIndex("StudentId");

                    b.ToTable("Marks");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f40c81e5-1f6a-44ea-a80d-c7f0a80916e4"),
                            AssessmentId = new Guid("78fdc1b0-b9ae-4010-827b-c1e77b798f16"),
                            DateRecorded = new DateTime(2025, 10, 28, 6, 38, 20, 839, DateTimeKind.Utc).AddTicks(2742),
                            IsResit = false,
                            RecordedByStaffId = new Guid("f95c9422-f66f-4c6e-9336-bfd0dccd8880"),
                            Score = 85m,
                            StudentId = new Guid("15be45ef-25e3-408b-b44e-3393157f70d1")
                        },
                        new
                        {
                            Id = new Guid("6386d3b4-320f-41c4-8312-ededde69a99f"),
                            AssessmentId = new Guid("83fcd674-ce89-4976-9ac1-2ceee1b05adb"),
                            DateRecorded = new DateTime(2025, 11, 18, 6, 38, 20, 839, DateTimeKind.Utc).AddTicks(2758),
                            IsResit = false,
                            RecordedByStaffId = new Guid("f95c9422-f66f-4c6e-9336-bfd0dccd8880"),
                            Score = 92m,
                            StudentId = new Guid("15be45ef-25e3-408b-b44e-3393157f70d1")
                        },
                        new
                        {
                            Id = new Guid("cfa7b661-06da-46fc-8814-a6923600e23e"),
                            AssessmentId = new Guid("67b98fcc-e250-49d1-938e-2770a43768df"),
                            DateRecorded = new DateTime(2025, 11, 8, 6, 38, 20, 839, DateTimeKind.Utc).AddTicks(2767),
                            IsResit = false,
                            RecordedByStaffId = new Guid("99ef4e44-05ae-44ef-937c-24d259268ac4"),
                            Score = 78m,
                            StudentId = new Guid("15be45ef-25e3-408b-b44e-3393157f70d1")
                        },
                        new
                        {
                            Id = new Guid("61077330-02e3-4629-94ce-ae55c3a23471"),
                            AssessmentId = new Guid("337ee3fc-b775-4b98-9f67-fcb8b7a20535"),
                            DateRecorded = new DateTime(2025, 11, 18, 6, 38, 20, 839, DateTimeKind.Utc).AddTicks(2774),
                            IsResit = false,
                            Score = 95m,
                            StudentId = new Guid("15be45ef-25e3-408b-b44e-3393157f70d1")
                        },
                        new
                        {
                            Id = new Guid("2abd2457-093f-4b51-abae-c633c17ddc0e"),
                            AssessmentId = new Guid("83fcd674-ce89-4976-9ac1-2ceee1b05adb"),
                            DateRecorded = new DateTime(2025, 11, 18, 6, 38, 20, 839, DateTimeKind.Utc).AddTicks(2779),
                            IsResit = false,
                            RecordedByStaffId = new Guid("f95c9422-f66f-4c6e-9336-bfd0dccd8880"),
                            Score = 35m,
                            StudentId = new Guid("6cd6224e-06be-4b8b-9000-8c2f896e1146")
                        },
                        new
                        {
                            Id = new Guid("6e1a0860-e45e-48a0-930c-04174d9d3678"),
                            AssessmentId = new Guid("83fcd674-ce89-4976-9ac1-2ceee1b05adb"),
                            Comments = "Resit passed.",
                            DateRecorded = new DateTime(2025, 12, 2, 6, 38, 20, 839, DateTimeKind.Utc).AddTicks(2789),
                            IsResit = true,
                            RecordedByStaffId = new Guid("f95c9422-f66f-4c6e-9336-bfd0dccd8880"),
                            Score = 65m,
                            StudentId = new Guid("6cd6224e-06be-4b8b-9000-8c2f896e1146")
                        },
                        new
                        {
                            Id = new Guid("7bbdf417-2e4a-4aa0-b860-1c6c775706a2"),
                            AssessmentId = new Guid("8c375ce0-db86-4fe7-9ed7-52f555e4b652"),
                            DateRecorded = new DateTime(2025, 11, 23, 6, 38, 20, 839, DateTimeKind.Utc).AddTicks(2839),
                            IsResit = false,
                            RecordedByStaffId = new Guid("99ef4e44-05ae-44ef-937c-24d259268ac4"),
                            Score = 70m,
                            StudentId = new Guid("6cd6224e-06be-4b8b-9000-8c2f896e1146")
                        },
                        new
                        {
                            Id = new Guid("99b2653f-0e50-494d-83ae-e8eefdf7b77f"),
                            AssessmentId = new Guid("83fcd674-ce89-4976-9ac1-2ceee1b05adb"),
                            DateRecorded = new DateTime(2025, 11, 18, 6, 38, 20, 839, DateTimeKind.Utc).AddTicks(2844),
                            IsResit = false,
                            RecordedByStaffId = new Guid("f95c9422-f66f-4c6e-9336-bfd0dccd8880"),
                            Score = 98m,
                            StudentId = new Guid("a88217fb-16ad-4875-9814-b6e739a8a5df")
                        },
                        new
                        {
                            Id = new Guid("d4cb1ad3-f7d9-425f-b1f0-7f899d57a7ba"),
                            AssessmentId = new Guid("06a330f0-6c03-46ad-89fc-e3bccb61a4a4"),
                            DateRecorded = new DateTime(2025, 11, 13, 6, 38, 20, 839, DateTimeKind.Utc).AddTicks(2852),
                            IsResit = false,
                            RecordedByStaffId = new Guid("f95c9422-f66f-4c6e-9336-bfd0dccd8880"),
                            Score = 88m,
                            StudentId = new Guid("a88217fb-16ad-4875-9814-b6e739a8a5df")
                        },
                        new
                        {
                            Id = new Guid("73cc7ed8-a9de-4f71-b427-ce076b311181"),
                            AssessmentId = new Guid("337ee3fc-b775-4b98-9f67-fcb8b7a20535"),
                            DateRecorded = new DateTime(2025, 11, 18, 6, 38, 20, 839, DateTimeKind.Utc).AddTicks(2864),
                            IsResit = false,
                            Score = 30m,
                            StudentId = new Guid("c72c0cdf-5c3f-4c07-97ff-7bb3243a4f0e")
                        },
                        new
                        {
                            Id = new Guid("9d4b93dc-62fd-4934-bae3-4bf5c31adc83"),
                            AssessmentId = new Guid("337ee3fc-b775-4b98-9f67-fcb8b7a20535"),
                            Comments = "Resit failed to meet passing threshold.",
                            DateRecorded = new DateTime(2025, 12, 12, 6, 38, 20, 839, DateTimeKind.Utc).AddTicks(2870),
                            IsResit = true,
                            Score = 38m,
                            StudentId = new Guid("c72c0cdf-5c3f-4c07-97ff-7bb3243a4f0e")
                        },
                        new
                        {
                            Id = new Guid("8ecfe0fb-a26c-4b27-bca9-c30447085ebe"),
                            AssessmentId = new Guid("78fdc1b0-b9ae-4010-827b-c1e77b798f16"),
                            DateRecorded = new DateTime(2025, 10, 28, 6, 38, 20, 839, DateTimeKind.Utc).AddTicks(2876),
                            IsResit = false,
                            RecordedByStaffId = new Guid("f95c9422-f66f-4c6e-9336-bfd0dccd8880"),
                            Score = 70m,
                            StudentId = new Guid("74b46aa9-b25b-4793-bf10-b3adaae5a2b3")
                        },
                        new
                        {
                            Id = new Guid("b78e4709-6d92-4d5d-b010-4f4f612f33ef"),
                            AssessmentId = new Guid("83fcd674-ce89-4976-9ac1-2ceee1b05adb"),
                            DateRecorded = new DateTime(2025, 11, 18, 6, 38, 20, 839, DateTimeKind.Utc).AddTicks(2881),
                            IsResit = false,
                            RecordedByStaffId = new Guid("f95c9422-f66f-4c6e-9336-bfd0dccd8880"),
                            Score = 75m,
                            StudentId = new Guid("74b46aa9-b25b-4793-bf10-b3adaae5a2b3")
                        });
                });

            modelBuilder.Entity("AuroraUniversity.Domain.Entities.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ModuleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StaffId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ModuleId");

                    b.HasIndex("StaffId");

                    b.ToTable("Sessions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("be3a92e2-6ace-43cc-ada8-62a1a26874d8"),
                            EndTime = new DateTime(2025, 9, 3, 12, 0, 0, 0, DateTimeKind.Utc),
                            Location = "Lecture Hall A",
                            ModuleId = new Guid("b2a8a3ee-ad46-4ef3-80a7-a756e7b4bb07"),
                            StaffId = new Guid("f95c9422-f66f-4c6e-9336-bfd0dccd8880"),
                            StartTime = new DateTime(2025, 9, 3, 10, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("41cff357-3345-4b9c-8058-a6aa238da882"),
                            EndTime = new DateTime(2025, 9, 4, 16, 0, 0, 0, DateTimeKind.Utc),
                            Location = "Seminar Room 101",
                            ModuleId = new Guid("b2a8a3ee-ad46-4ef3-80a7-a756e7b4bb07"),
                            StaffId = new Guid("f95c9422-f66f-4c6e-9336-bfd0dccd8880"),
                            StartTime = new DateTime(2025, 9, 4, 14, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("7f74f7b1-5375-4dde-9e78-0efc146e2cb1"),
                            EndTime = new DateTime(2025, 9, 5, 11, 0, 0, 0, DateTimeKind.Utc),
                            Location = "Lecture Hall B",
                            ModuleId = new Guid("6983138a-93e7-4171-95bc-61ce2fb7cdae"),
                            StaffId = new Guid("99ef4e44-05ae-44ef-937c-24d259268ac4"),
                            StartTime = new DateTime(2025, 9, 5, 9, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("327cbcfa-8e58-4c7b-9db8-2e621110bae1"),
                            EndTime = new DateTime(2025, 9, 6, 15, 0, 0, 0, DateTimeKind.Utc),
                            Location = "Lab 205",
                            ModuleId = new Guid("6983138a-93e7-4171-95bc-61ce2fb7cdae"),
                            StaffId = new Guid("99ef4e44-05ae-44ef-937c-24d259268ac4"),
                            StartTime = new DateTime(2025, 9, 6, 13, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("3bbc0948-cd32-4768-90d8-6833a3243ae4"),
                            EndTime = new DateTime(2025, 9, 8, 13, 0, 0, 0, DateTimeKind.Utc),
                            Location = "Virtual Classroom",
                            ModuleId = new Guid("60f08462-e923-4908-9eea-a27651a14b10"),
                            StaffId = new Guid("692c3f01-aed7-4541-b207-d815e5e1efd8"),
                            StartTime = new DateTime(2025, 9, 8, 11, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("59ac3936-4ef7-4826-ba8c-ee60aecc86ef"),
                            EndTime = new DateTime(2025, 9, 9, 18, 0, 0, 0, DateTimeKind.Utc),
                            Location = "Lab 103",
                            ModuleId = new Guid("60f08462-e923-4908-9eea-a27651a14b10"),
                            StaffId = new Guid("692c3f01-aed7-4541-b207-d815e5e1efd8"),
                            StartTime = new DateTime(2025, 9, 9, 16, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("3f5a49c5-e457-41a6-8270-f52051d1ba92"),
                            EndTime = new DateTime(2025, 9, 10, 12, 0, 0, 0, DateTimeKind.Utc),
                            Location = "Lecture Hall C",
                            ModuleId = new Guid("7616de2f-756c-4c5e-b49a-8561637c9451"),
                            StaffId = new Guid("f95c9422-f66f-4c6e-9336-bfd0dccd8880"),
                            StartTime = new DateTime(2025, 9, 10, 10, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("ad029dce-1670-4634-b4bc-fb3c4c421bd0"),
                            EndTime = new DateTime(2025, 9, 11, 15, 0, 0, 0, DateTimeKind.Utc),
                            Location = "Seminar Room 202",
                            ModuleId = new Guid("7616de2f-756c-4c5e-b49a-8561637c9451"),
                            StaffId = new Guid("f95c9422-f66f-4c6e-9336-bfd0dccd8880"),
                            StartTime = new DateTime(2025, 9, 11, 13, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("AuroraUniversity.Domain.Entities.Staff", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Staffs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f95c9422-f66f-4c6e-9336-bfd0dccd8880"),
                            Email = "alice@aurora.edu",
                            FirstName = "Alice",
                            LastName = "Smith"
                        },
                        new
                        {
                            Id = new Guid("99ef4e44-05ae-44ef-937c-24d259268ac4"),
                            Email = "bob@aurora.edu",
                            FirstName = "Bob",
                            LastName = "Johnson"
                        },
                        new
                        {
                            Id = new Guid("692c3f01-aed7-4541-b207-d815e5e1efd8"),
                            Email = "carol@aurora.edu",
                            FirstName = "Carol",
                            LastName = "Davis"
                        });
                });

            modelBuilder.Entity("AuroraUniversity.Domain.Entities.Student", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = new Guid("15be45ef-25e3-408b-b44e-3393157f70d1"),
                            FirstName = "Olivia",
                            LastName = "Chen"
                        },
                        new
                        {
                            Id = new Guid("6cd6224e-06be-4b8b-9000-8c2f896e1146"),
                            FirstName = "Liam",
                            LastName = "Johnson"
                        },
                        new
                        {
                            Id = new Guid("a88217fb-16ad-4875-9814-b6e739a8a5df"),
                            FirstName = "Emma",
                            LastName = "Schmidt"
                        },
                        new
                        {
                            Id = new Guid("c72c0cdf-5c3f-4c07-97ff-7bb3243a4f0e"),
                            FirstName = "Noah",
                            LastName = "Silva"
                        },
                        new
                        {
                            Id = new Guid("74b46aa9-b25b-4793-bf10-b3adaae5a2b3"),
                            FirstName = "Ava",
                            LastName = "Dubois"
                        },
                        new
                        {
                            Id = new Guid("4fd26caa-574f-4102-b87b-790a5762508f"),
                            FirstName = "Isabelle",
                            LastName = "Kim"
                        },
                        new
                        {
                            Id = new Guid("f41bbb0a-72fc-4c2c-850d-9cc621bf9964"),
                            FirstName = "Lucas",
                            LastName = "Garcia"
                        },
                        new
                        {
                            Id = new Guid("cc3a1dff-3b00-42f0-924a-073b7f2847ea"),
                            FirstName = "Mia",
                            LastName = "Rossi"
                        },
                        new
                        {
                            Id = new Guid("549a1ad2-8ad5-47f4-bdb1-05ebe8db7c62"),
                            FirstName = "Elijah",
                            LastName = "Patel"
                        },
                        new
                        {
                            Id = new Guid("14ebecc9-c94b-4aa3-a16c-da4e37b8d721"),
                            FirstName = "Sophia",
                            LastName = "Müller"
                        });
                });

            modelBuilder.Entity("AuroraUniversity.Domain.Entities.Term", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Terms");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3c137947-2892-4f57-9eeb-d4931cba03b1"),
                            Code = "TRM1",
                            EndTime = new DateTime(2025, 12, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            StartTime = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Term 1"
                        });
                });

            modelBuilder.Entity("AuroraUniversity.Domain.Entities.TermModule", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Credits")
                        .HasColumnType("integer");

                    b.Property<Guid>("StaffId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TermId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("StaffId");

                    b.HasIndex("TermId");

                    b.ToTable("Modules");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b2a8a3ee-ad46-4ef3-80a7-a756e7b4bb07"),
                            Capacity = 30,
                            Code = "MATH101",
                            Credits = 4,
                            StaffId = new Guid("f95c9422-f66f-4c6e-9336-bfd0dccd8880"),
                            TermId = new Guid("3c137947-2892-4f57-9eeb-d4931cba03b1"),
                            Title = "Mathematics I"
                        },
                        new
                        {
                            Id = new Guid("6983138a-93e7-4171-95bc-61ce2fb7cdae"),
                            Capacity = 25,
                            Code = "PHYS102",
                            Credits = 3,
                            StaffId = new Guid("99ef4e44-05ae-44ef-937c-24d259268ac4"),
                            TermId = new Guid("3c137947-2892-4f57-9eeb-d4931cba03b1"),
                            Title = "Physics I"
                        },
                        new
                        {
                            Id = new Guid("60f08462-e923-4908-9eea-a27651a14b10"),
                            Capacity = 35,
                            Code = "CS103",
                            Credits = 3,
                            StaffId = new Guid("692c3f01-aed7-4541-b207-d815e5e1efd8"),
                            TermId = new Guid("3c137947-2892-4f57-9eeb-d4931cba03b1"),
                            Title = "Intro to Programming"
                        },
                        new
                        {
                            Id = new Guid("7616de2f-756c-4c5e-b49a-8561637c9451"),
                            Capacity = 20,
                            Code = "STAT104",
                            Credits = 2,
                            StaffId = new Guid("f95c9422-f66f-4c6e-9336-bfd0dccd8880"),
                            TermId = new Guid("3c137947-2892-4f57-9eeb-d4931cba03b1"),
                            Title = "Statistics"
                        });
                });

            modelBuilder.Entity("SessionStudent", b =>
                {
                    b.Property<Guid>("RegisteredSessionsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RegisteredStudentsId")
                        .HasColumnType("uuid");

                    b.HasKey("RegisteredSessionsId", "RegisteredStudentsId");

                    b.HasIndex("RegisteredStudentsId");

                    b.ToTable("SessionStudent");

                    b.HasData(
                        new
                        {
                            RegisteredSessionsId = new Guid("be3a92e2-6ace-43cc-ada8-62a1a26874d8"),
                            RegisteredStudentsId = new Guid("15be45ef-25e3-408b-b44e-3393157f70d1")
                        },
                        new
                        {
                            RegisteredSessionsId = new Guid("be3a92e2-6ace-43cc-ada8-62a1a26874d8"),
                            RegisteredStudentsId = new Guid("6cd6224e-06be-4b8b-9000-8c2f896e1146")
                        },
                        new
                        {
                            RegisteredSessionsId = new Guid("be3a92e2-6ace-43cc-ada8-62a1a26874d8"),
                            RegisteredStudentsId = new Guid("a88217fb-16ad-4875-9814-b6e739a8a5df")
                        },
                        new
                        {
                            RegisteredSessionsId = new Guid("be3a92e2-6ace-43cc-ada8-62a1a26874d8"),
                            RegisteredStudentsId = new Guid("c72c0cdf-5c3f-4c07-97ff-7bb3243a4f0e")
                        },
                        new
                        {
                            RegisteredSessionsId = new Guid("be3a92e2-6ace-43cc-ada8-62a1a26874d8"),
                            RegisteredStudentsId = new Guid("74b46aa9-b25b-4793-bf10-b3adaae5a2b3")
                        },
                        new
                        {
                            RegisteredSessionsId = new Guid("be3a92e2-6ace-43cc-ada8-62a1a26874d8"),
                            RegisteredStudentsId = new Guid("4fd26caa-574f-4102-b87b-790a5762508f")
                        },
                        new
                        {
                            RegisteredSessionsId = new Guid("be3a92e2-6ace-43cc-ada8-62a1a26874d8"),
                            RegisteredStudentsId = new Guid("f41bbb0a-72fc-4c2c-850d-9cc621bf9964")
                        },
                        new
                        {
                            RegisteredSessionsId = new Guid("be3a92e2-6ace-43cc-ada8-62a1a26874d8"),
                            RegisteredStudentsId = new Guid("cc3a1dff-3b00-42f0-924a-073b7f2847ea")
                        },
                        new
                        {
                            RegisteredSessionsId = new Guid("be3a92e2-6ace-43cc-ada8-62a1a26874d8"),
                            RegisteredStudentsId = new Guid("549a1ad2-8ad5-47f4-bdb1-05ebe8db7c62")
                        },
                        new
                        {
                            RegisteredSessionsId = new Guid("be3a92e2-6ace-43cc-ada8-62a1a26874d8"),
                            RegisteredStudentsId = new Guid("14ebecc9-c94b-4aa3-a16c-da4e37b8d721")
                        },
                        new
                        {
                            RegisteredSessionsId = new Guid("7f74f7b1-5375-4dde-9e78-0efc146e2cb1"),
                            RegisteredStudentsId = new Guid("15be45ef-25e3-408b-b44e-3393157f70d1")
                        },
                        new
                        {
                            RegisteredSessionsId = new Guid("7f74f7b1-5375-4dde-9e78-0efc146e2cb1"),
                            RegisteredStudentsId = new Guid("6cd6224e-06be-4b8b-9000-8c2f896e1146")
                        },
                        new
                        {
                            RegisteredSessionsId = new Guid("7f74f7b1-5375-4dde-9e78-0efc146e2cb1"),
                            RegisteredStudentsId = new Guid("a88217fb-16ad-4875-9814-b6e739a8a5df")
                        },
                        new
                        {
                            RegisteredSessionsId = new Guid("7f74f7b1-5375-4dde-9e78-0efc146e2cb1"),
                            RegisteredStudentsId = new Guid("c72c0cdf-5c3f-4c07-97ff-7bb3243a4f0e")
                        },
                        new
                        {
                            RegisteredSessionsId = new Guid("7f74f7b1-5375-4dde-9e78-0efc146e2cb1"),
                            RegisteredStudentsId = new Guid("74b46aa9-b25b-4793-bf10-b3adaae5a2b3")
                        },
                        new
                        {
                            RegisteredSessionsId = new Guid("7f74f7b1-5375-4dde-9e78-0efc146e2cb1"),
                            RegisteredStudentsId = new Guid("4fd26caa-574f-4102-b87b-790a5762508f")
                        },
                        new
                        {
                            RegisteredSessionsId = new Guid("7f74f7b1-5375-4dde-9e78-0efc146e2cb1"),
                            RegisteredStudentsId = new Guid("f41bbb0a-72fc-4c2c-850d-9cc621bf9964")
                        },
                        new
                        {
                            RegisteredSessionsId = new Guid("7f74f7b1-5375-4dde-9e78-0efc146e2cb1"),
                            RegisteredStudentsId = new Guid("cc3a1dff-3b00-42f0-924a-073b7f2847ea")
                        },
                        new
                        {
                            RegisteredSessionsId = new Guid("7f74f7b1-5375-4dde-9e78-0efc146e2cb1"),
                            RegisteredStudentsId = new Guid("549a1ad2-8ad5-47f4-bdb1-05ebe8db7c62")
                        },
                        new
                        {
                            RegisteredSessionsId = new Guid("7f74f7b1-5375-4dde-9e78-0efc146e2cb1"),
                            RegisteredStudentsId = new Guid("14ebecc9-c94b-4aa3-a16c-da4e37b8d721")
                        },
                        new
                        {
                            RegisteredSessionsId = new Guid("3bbc0948-cd32-4768-90d8-6833a3243ae4"),
                            RegisteredStudentsId = new Guid("15be45ef-25e3-408b-b44e-3393157f70d1")
                        },
                        new
                        {
                            RegisteredSessionsId = new Guid("3bbc0948-cd32-4768-90d8-6833a3243ae4"),
                            RegisteredStudentsId = new Guid("6cd6224e-06be-4b8b-9000-8c2f896e1146")
                        },
                        new
                        {
                            RegisteredSessionsId = new Guid("3bbc0948-cd32-4768-90d8-6833a3243ae4"),
                            RegisteredStudentsId = new Guid("a88217fb-16ad-4875-9814-b6e739a8a5df")
                        },
                        new
                        {
                            RegisteredSessionsId = new Guid("3bbc0948-cd32-4768-90d8-6833a3243ae4"),
                            RegisteredStudentsId = new Guid("c72c0cdf-5c3f-4c07-97ff-7bb3243a4f0e")
                        },
                        new
                        {
                            RegisteredSessionsId = new Guid("3bbc0948-cd32-4768-90d8-6833a3243ae4"),
                            RegisteredStudentsId = new Guid("74b46aa9-b25b-4793-bf10-b3adaae5a2b3")
                        },
                        new
                        {
                            RegisteredSessionsId = new Guid("3bbc0948-cd32-4768-90d8-6833a3243ae4"),
                            RegisteredStudentsId = new Guid("4fd26caa-574f-4102-b87b-790a5762508f")
                        },
                        new
                        {
                            RegisteredSessionsId = new Guid("3bbc0948-cd32-4768-90d8-6833a3243ae4"),
                            RegisteredStudentsId = new Guid("f41bbb0a-72fc-4c2c-850d-9cc621bf9964")
                        },
                        new
                        {
                            RegisteredSessionsId = new Guid("3bbc0948-cd32-4768-90d8-6833a3243ae4"),
                            RegisteredStudentsId = new Guid("cc3a1dff-3b00-42f0-924a-073b7f2847ea")
                        },
                        new
                        {
                            RegisteredSessionsId = new Guid("3bbc0948-cd32-4768-90d8-6833a3243ae4"),
                            RegisteredStudentsId = new Guid("549a1ad2-8ad5-47f4-bdb1-05ebe8db7c62")
                        },
                        new
                        {
                            RegisteredSessionsId = new Guid("3bbc0948-cd32-4768-90d8-6833a3243ae4"),
                            RegisteredStudentsId = new Guid("14ebecc9-c94b-4aa3-a16c-da4e37b8d721")
                        },
                        new
                        {
                            RegisteredSessionsId = new Guid("3f5a49c5-e457-41a6-8270-f52051d1ba92"),
                            RegisteredStudentsId = new Guid("15be45ef-25e3-408b-b44e-3393157f70d1")
                        },
                        new
                        {
                            RegisteredSessionsId = new Guid("3f5a49c5-e457-41a6-8270-f52051d1ba92"),
                            RegisteredStudentsId = new Guid("6cd6224e-06be-4b8b-9000-8c2f896e1146")
                        },
                        new
                        {
                            RegisteredSessionsId = new Guid("3f5a49c5-e457-41a6-8270-f52051d1ba92"),
                            RegisteredStudentsId = new Guid("a88217fb-16ad-4875-9814-b6e739a8a5df")
                        },
                        new
                        {
                            RegisteredSessionsId = new Guid("3f5a49c5-e457-41a6-8270-f52051d1ba92"),
                            RegisteredStudentsId = new Guid("c72c0cdf-5c3f-4c07-97ff-7bb3243a4f0e")
                        },
                        new
                        {
                            RegisteredSessionsId = new Guid("3f5a49c5-e457-41a6-8270-f52051d1ba92"),
                            RegisteredStudentsId = new Guid("74b46aa9-b25b-4793-bf10-b3adaae5a2b3")
                        });
                });

            modelBuilder.Entity("StudentTermModule", b =>
                {
                    b.Property<Guid>("EnrolledModulesId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EnrolledStudentsId")
                        .HasColumnType("uuid");

                    b.HasKey("EnrolledModulesId", "EnrolledStudentsId");

                    b.HasIndex("EnrolledStudentsId");

                    b.ToTable("StudentTermModule");

                    b.HasData(
                        new
                        {
                            EnrolledModulesId = new Guid("b2a8a3ee-ad46-4ef3-80a7-a756e7b4bb07"),
                            EnrolledStudentsId = new Guid("15be45ef-25e3-408b-b44e-3393157f70d1")
                        },
                        new
                        {
                            EnrolledModulesId = new Guid("6983138a-93e7-4171-95bc-61ce2fb7cdae"),
                            EnrolledStudentsId = new Guid("15be45ef-25e3-408b-b44e-3393157f70d1")
                        },
                        new
                        {
                            EnrolledModulesId = new Guid("60f08462-e923-4908-9eea-a27651a14b10"),
                            EnrolledStudentsId = new Guid("15be45ef-25e3-408b-b44e-3393157f70d1")
                        },
                        new
                        {
                            EnrolledModulesId = new Guid("7616de2f-756c-4c5e-b49a-8561637c9451"),
                            EnrolledStudentsId = new Guid("15be45ef-25e3-408b-b44e-3393157f70d1")
                        },
                        new
                        {
                            EnrolledModulesId = new Guid("b2a8a3ee-ad46-4ef3-80a7-a756e7b4bb07"),
                            EnrolledStudentsId = new Guid("6cd6224e-06be-4b8b-9000-8c2f896e1146")
                        },
                        new
                        {
                            EnrolledModulesId = new Guid("6983138a-93e7-4171-95bc-61ce2fb7cdae"),
                            EnrolledStudentsId = new Guid("6cd6224e-06be-4b8b-9000-8c2f896e1146")
                        },
                        new
                        {
                            EnrolledModulesId = new Guid("60f08462-e923-4908-9eea-a27651a14b10"),
                            EnrolledStudentsId = new Guid("6cd6224e-06be-4b8b-9000-8c2f896e1146")
                        },
                        new
                        {
                            EnrolledModulesId = new Guid("7616de2f-756c-4c5e-b49a-8561637c9451"),
                            EnrolledStudentsId = new Guid("6cd6224e-06be-4b8b-9000-8c2f896e1146")
                        },
                        new
                        {
                            EnrolledModulesId = new Guid("b2a8a3ee-ad46-4ef3-80a7-a756e7b4bb07"),
                            EnrolledStudentsId = new Guid("a88217fb-16ad-4875-9814-b6e739a8a5df")
                        },
                        new
                        {
                            EnrolledModulesId = new Guid("6983138a-93e7-4171-95bc-61ce2fb7cdae"),
                            EnrolledStudentsId = new Guid("a88217fb-16ad-4875-9814-b6e739a8a5df")
                        },
                        new
                        {
                            EnrolledModulesId = new Guid("60f08462-e923-4908-9eea-a27651a14b10"),
                            EnrolledStudentsId = new Guid("a88217fb-16ad-4875-9814-b6e739a8a5df")
                        },
                        new
                        {
                            EnrolledModulesId = new Guid("7616de2f-756c-4c5e-b49a-8561637c9451"),
                            EnrolledStudentsId = new Guid("a88217fb-16ad-4875-9814-b6e739a8a5df")
                        },
                        new
                        {
                            EnrolledModulesId = new Guid("b2a8a3ee-ad46-4ef3-80a7-a756e7b4bb07"),
                            EnrolledStudentsId = new Guid("c72c0cdf-5c3f-4c07-97ff-7bb3243a4f0e")
                        },
                        new
                        {
                            EnrolledModulesId = new Guid("6983138a-93e7-4171-95bc-61ce2fb7cdae"),
                            EnrolledStudentsId = new Guid("c72c0cdf-5c3f-4c07-97ff-7bb3243a4f0e")
                        },
                        new
                        {
                            EnrolledModulesId = new Guid("60f08462-e923-4908-9eea-a27651a14b10"),
                            EnrolledStudentsId = new Guid("c72c0cdf-5c3f-4c07-97ff-7bb3243a4f0e")
                        },
                        new
                        {
                            EnrolledModulesId = new Guid("7616de2f-756c-4c5e-b49a-8561637c9451"),
                            EnrolledStudentsId = new Guid("c72c0cdf-5c3f-4c07-97ff-7bb3243a4f0e")
                        },
                        new
                        {
                            EnrolledModulesId = new Guid("b2a8a3ee-ad46-4ef3-80a7-a756e7b4bb07"),
                            EnrolledStudentsId = new Guid("74b46aa9-b25b-4793-bf10-b3adaae5a2b3")
                        },
                        new
                        {
                            EnrolledModulesId = new Guid("6983138a-93e7-4171-95bc-61ce2fb7cdae"),
                            EnrolledStudentsId = new Guid("74b46aa9-b25b-4793-bf10-b3adaae5a2b3")
                        },
                        new
                        {
                            EnrolledModulesId = new Guid("60f08462-e923-4908-9eea-a27651a14b10"),
                            EnrolledStudentsId = new Guid("74b46aa9-b25b-4793-bf10-b3adaae5a2b3")
                        },
                        new
                        {
                            EnrolledModulesId = new Guid("7616de2f-756c-4c5e-b49a-8561637c9451"),
                            EnrolledStudentsId = new Guid("74b46aa9-b25b-4793-bf10-b3adaae5a2b3")
                        },
                        new
                        {
                            EnrolledModulesId = new Guid("b2a8a3ee-ad46-4ef3-80a7-a756e7b4bb07"),
                            EnrolledStudentsId = new Guid("4fd26caa-574f-4102-b87b-790a5762508f")
                        },
                        new
                        {
                            EnrolledModulesId = new Guid("6983138a-93e7-4171-95bc-61ce2fb7cdae"),
                            EnrolledStudentsId = new Guid("4fd26caa-574f-4102-b87b-790a5762508f")
                        },
                        new
                        {
                            EnrolledModulesId = new Guid("60f08462-e923-4908-9eea-a27651a14b10"),
                            EnrolledStudentsId = new Guid("4fd26caa-574f-4102-b87b-790a5762508f")
                        },
                        new
                        {
                            EnrolledModulesId = new Guid("b2a8a3ee-ad46-4ef3-80a7-a756e7b4bb07"),
                            EnrolledStudentsId = new Guid("f41bbb0a-72fc-4c2c-850d-9cc621bf9964")
                        },
                        new
                        {
                            EnrolledModulesId = new Guid("6983138a-93e7-4171-95bc-61ce2fb7cdae"),
                            EnrolledStudentsId = new Guid("f41bbb0a-72fc-4c2c-850d-9cc621bf9964")
                        },
                        new
                        {
                            EnrolledModulesId = new Guid("60f08462-e923-4908-9eea-a27651a14b10"),
                            EnrolledStudentsId = new Guid("f41bbb0a-72fc-4c2c-850d-9cc621bf9964")
                        },
                        new
                        {
                            EnrolledModulesId = new Guid("b2a8a3ee-ad46-4ef3-80a7-a756e7b4bb07"),
                            EnrolledStudentsId = new Guid("cc3a1dff-3b00-42f0-924a-073b7f2847ea")
                        },
                        new
                        {
                            EnrolledModulesId = new Guid("6983138a-93e7-4171-95bc-61ce2fb7cdae"),
                            EnrolledStudentsId = new Guid("cc3a1dff-3b00-42f0-924a-073b7f2847ea")
                        },
                        new
                        {
                            EnrolledModulesId = new Guid("60f08462-e923-4908-9eea-a27651a14b10"),
                            EnrolledStudentsId = new Guid("cc3a1dff-3b00-42f0-924a-073b7f2847ea")
                        },
                        new
                        {
                            EnrolledModulesId = new Guid("b2a8a3ee-ad46-4ef3-80a7-a756e7b4bb07"),
                            EnrolledStudentsId = new Guid("549a1ad2-8ad5-47f4-bdb1-05ebe8db7c62")
                        },
                        new
                        {
                            EnrolledModulesId = new Guid("6983138a-93e7-4171-95bc-61ce2fb7cdae"),
                            EnrolledStudentsId = new Guid("549a1ad2-8ad5-47f4-bdb1-05ebe8db7c62")
                        },
                        new
                        {
                            EnrolledModulesId = new Guid("60f08462-e923-4908-9eea-a27651a14b10"),
                            EnrolledStudentsId = new Guid("549a1ad2-8ad5-47f4-bdb1-05ebe8db7c62")
                        },
                        new
                        {
                            EnrolledModulesId = new Guid("b2a8a3ee-ad46-4ef3-80a7-a756e7b4bb07"),
                            EnrolledStudentsId = new Guid("14ebecc9-c94b-4aa3-a16c-da4e37b8d721")
                        },
                        new
                        {
                            EnrolledModulesId = new Guid("6983138a-93e7-4171-95bc-61ce2fb7cdae"),
                            EnrolledStudentsId = new Guid("14ebecc9-c94b-4aa3-a16c-da4e37b8d721")
                        },
                        new
                        {
                            EnrolledModulesId = new Guid("60f08462-e923-4908-9eea-a27651a14b10"),
                            EnrolledStudentsId = new Guid("14ebecc9-c94b-4aa3-a16c-da4e37b8d721")
                        });
                });

            modelBuilder.Entity("AuroraUniversity.Domain.Entities.Assessment", b =>
                {
                    b.HasOne("AuroraUniversity.Domain.Entities.TermModule", "Module")
                        .WithMany("Assessments")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Module");
                });

            modelBuilder.Entity("AuroraUniversity.Domain.Entities.Mark", b =>
                {
                    b.HasOne("AuroraUniversity.Domain.Entities.Assessment", "Assessment")
                        .WithMany("Marks")
                        .HasForeignKey("AssessmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AuroraUniversity.Domain.Entities.Staff", "RecordedByStaff")
                        .WithMany()
                        .HasForeignKey("RecordedByStaffId");

                    b.HasOne("AuroraUniversity.Domain.Entities.Student", "Student")
                        .WithMany("Marks")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assessment");

                    b.Navigation("RecordedByStaff");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("AuroraUniversity.Domain.Entities.Session", b =>
                {
                    b.HasOne("AuroraUniversity.Domain.Entities.TermModule", "Module")
                        .WithMany("Sessions")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AuroraUniversity.Domain.Entities.Staff", "Staff")
                        .WithMany("TaughtSessions")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Module");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("AuroraUniversity.Domain.Entities.TermModule", b =>
                {
                    b.HasOne("AuroraUniversity.Domain.Entities.Staff", "Staff")
                        .WithMany("ManagedModules")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AuroraUniversity.Domain.Entities.Term", "Term")
                        .WithMany("Modules")
                        .HasForeignKey("TermId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Staff");

                    b.Navigation("Term");
                });

            modelBuilder.Entity("SessionStudent", b =>
                {
                    b.HasOne("AuroraUniversity.Domain.Entities.Session", null)
                        .WithMany()
                        .HasForeignKey("RegisteredSessionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AuroraUniversity.Domain.Entities.Student", null)
                        .WithMany()
                        .HasForeignKey("RegisteredStudentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StudentTermModule", b =>
                {
                    b.HasOne("AuroraUniversity.Domain.Entities.TermModule", null)
                        .WithMany()
                        .HasForeignKey("EnrolledModulesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AuroraUniversity.Domain.Entities.Student", null)
                        .WithMany()
                        .HasForeignKey("EnrolledStudentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AuroraUniversity.Domain.Entities.Assessment", b =>
                {
                    b.Navigation("Marks");
                });

            modelBuilder.Entity("AuroraUniversity.Domain.Entities.Staff", b =>
                {
                    b.Navigation("ManagedModules");

                    b.Navigation("TaughtSessions");
                });

            modelBuilder.Entity("AuroraUniversity.Domain.Entities.Student", b =>
                {
                    b.Navigation("Marks");
                });

            modelBuilder.Entity("AuroraUniversity.Domain.Entities.Term", b =>
                {
                    b.Navigation("Modules");
                });

            modelBuilder.Entity("AuroraUniversity.Domain.Entities.TermModule", b =>
                {
                    b.Navigation("Assessments");

                    b.Navigation("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
